// Generates `src/embedded.ts` from the built SPA in `web/dist/`.
// Emits static `import ... with { type: "file" }` statements so that
// `bun build --compile` can bake each asset into the final binary.

import { readdir, stat } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DIST_DIR = join(ROOT, "web", "dist");
const OUT_FILE = join(ROOT, "src", "embedded.ts");

const CONTENT_TYPES: Record<string, string> = {
  html: "text/html; charset=utf-8",
  js: "application/javascript",
  mjs: "application/javascript",
  css: "text/css",
  svg: "image/svg+xml",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  ico: "image/x-icon",
  json: "application/json",
  map: "application/json",
  txt: "text/plain; charset=utf-8",
  woff: "font/woff",
  woff2: "font/woff2",
  ttf: "font/ttf",
  otf: "font/otf",
  wasm: "application/wasm",
};

function contentTypeFor(path: string): string {
  const dot = path.lastIndexOf(".");
  if (dot === -1) return "application/octet-stream";
  const ext = path.slice(dot + 1).toLowerCase();
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return out;
    throw err;
  }
  for (const name of entries) {
    const full = join(dir, name);
    const s = await stat(full);
    if (s.isDirectory()) {
      out.push(...(await walk(full)));
    } else if (s.isFile()) {
      out.push(full);
    }
  }
  return out;
}

async function totalSize(paths: string[]): Promise<number> {
  let total = 0;
  for (const p of paths) {
    const s = await stat(p);
    total += s.size;
  }
  return total;
}

function urlPathFor(relPath: string): string {
  return "/" + relPath.split("\\").join("/").replace(/^\/+/, "");
}

function importPathFor(relPath: string): string {
  return "../web/dist/" + relPath.split("\\").join("/").replace(/^\/+/, "");
}

async function main() {
  const files = (await walk(DIST_DIR)).sort();
  if (files.length === 0) {
    console.warn(`[embed-dist] no files found in ${DIST_DIR}; writing empty embedded map`);
  }

  const imports: string[] = [];
  const entries: string[] = [];
  let hasIndex = false;

  files.forEach((full, idx) => {
    const rel = relative(DIST_DIR, full);
    const url = urlPathFor(rel);
    const importPath = importPathFor(rel);
    const type = contentTypeFor(rel);
    const ident = `file_${idx}`;
    imports.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`);
    entries.push(`  ${JSON.stringify(url)}: { path: ${ident}, type: ${JSON.stringify(type)} },`);
    if (url === "/index.html") {
      hasIndex = true;
      entries.push(`  "/": { path: ${ident}, type: ${JSON.stringify(type)} },`);
    }
  });

  const source =
    "// Auto-generated by scripts/embed-dist.ts. Do not edit by hand.\n" +
    "// Regenerate with `bun run build:embed` (runs as part of `bun run build`).\n\n" +
    imports.join("\n") +
    (imports.length > 0 ? "\n\n" : "") +
    "export const embedded: Record<string, { path: string; type: string }> = {\n" +
    entries.join("\n") +
    (entries.length > 0 ? "\n" : "") +
    "};\n";

  await Bun.write(OUT_FILE, source);

  const size = await totalSize(files);
  const kb = (size / 1024).toFixed(1);
  console.log(
    `[embed-dist] wrote ${OUT_FILE} (${files.length} file(s), ${kb} KiB${hasIndex ? ", index aliased to /" : ""})`,
  );
}

await main();
