use std::net::Ipv4Addr;

use super::checksum_verify_snippet;

pub const COOLIFY_SCHEMA_SQL: &str = "CREATE TABLE service_endpoints (\n    container_id    TEXT NOT NULL DEFAULT '' PRIMARY KEY,\n    container_name  TEXT NOT NULL DEFAULT '',\n    namespace       TEXT NOT NULL DEFAULT '',\n    host_mgmt_ip    TEXT NOT NULL DEFAULT '',\n    container_ip    TEXT NOT NULL DEFAULT '',\n    state           TEXT NOT NULL DEFAULT '',\n    health          TEXT NOT NULL DEFAULT 'unknown',\n    updated_at      INTEGER NOT NULL DEFAULT 0\n);\n";

/// Directory + file paths for the OPT-IN shared gossip TLS material (S5).
pub const GOSSIP_TLS_DIR: &str = "/etc/corrosion/tls";
pub const GOSSIP_TLS_CERT_PATH: &str = "/etc/corrosion/tls/gossip.pem";
pub const GOSSIP_TLS_KEY_PATH: &str = "/etc/corrosion/tls/gossip.key";

/// Render the Corrosion agent config.
///
/// S5 (gossip authentication): Corrosion's SWIM gossip carries the
/// `service_endpoints` rows that drive cluster DNS and firewall decisions.
/// A forged row is cluster-wide DNS/firewall poisoning, so who can gossip
/// matters.
///
/// The ENFORCED trust boundary is the bind address, not TLS:
///
///   1. Always-on baseline: the gossip listener binds `bind_addr` — the host's
///      WireGuard **mgmt IP** — never `0.0.0.0`. Reaching the port therefore
///      requires membership in the encrypted, mutually-authenticated WireGuard
///      mesh; a host off the mesh cannot gossip at all. This binding is the
///      real trust boundary. (`bind_addr` must be a real mesh IP; an
///      unspecified address is refused by [`assert_mesh_bind`], which runs on
///      the single generation path every caller — plan + apply — routes
///      through.)
///
///   2. Opt-in (`gossip_tls = true`): additionally wrap gossip in a second TLS
///      layer using a shared self-signed cert provisioned to every node. This
///      is pure defense-in-depth ENCRYPTION on top of WireGuard; it does NOT
///      add per-node authentication. Corrosion v1.0.0's client verifier only
///      checks that a peer cert chains to a configured CA — it never checks
///      *which* node presented it — and because every node holds the same
///      shared cert/key, TLS cannot distinguish one mesh member from another.
///      See the note in [`gossip_tls_toml`] for why the config is
///      encryption-only (`insecure = true`, no `ca_file`, no
///      `[gossip.tls.client]`): that is the only shared-cert shape Corrosion
///      v1.0.0 will actually load and complete a cross-node QUIC handshake
///      with. Default provisioning leaves this OFF and the bytes are identical
///      to the historical plaintext config.
///
/// Residual trust assumption (both modes): every host on the WireGuard mesh is
/// trusted to write truthful `service_endpoints` rows. Gossip TLS does NOT
/// change this — only mesh membership does. Do not extend the mesh to hosts you
/// do not fully trust and expect gossip TLS to contain them.
pub fn config_bytes(
    bind_addr: Ipv4Addr,
    gossip_port: u16,
    api_port: u16,
    peers: &[Ipv4Addr],
    gossip_tls: bool,
) -> Vec<u8> {
    assert_mesh_bind(bind_addr);
    let mut sorted = peers.to_vec();
    sorted.sort();
    let bootstrap = sorted
        .iter()
        .map(|p| format!("\"{p}:{gossip_port}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let gossip_auth = if gossip_tls {
        gossip_tls_toml()
    } else {
        "plaintext = true".to_string()
    };
    format!("# generated by coolify — do not edit\n[db]\npath = \"/var/lib/corrosion/corrosion.db\"\nschema_paths = [\"/etc/corrosion/schemas\"]\n\n[gossip]\naddr = \"{bind_addr}:{gossip_port}\"\nbootstrap = [{bootstrap}]\n{gossip_auth}\n\n[api]\naddr = \"127.0.0.1:{api_port}\"\n\n[admin]\npath = \"/var/run/corrosion/admin.sock\"\n").into_bytes()
}

/// Render the opt-in `[gossip.tls]` block (S5).
///
/// Schema verified against Corrosion **v1.0.0** upstream — the pinned default
/// (`--corrosion-version v1.0.0`). Sources:
///   * `crates/corro-types/src/config.rs` — `GossipConfig { bind_addr (serde
///     alias "addr"), bootstrap, tls: Option<TlsConfig>, plaintext, .. }` and
///     `TlsConfig { cert_file, key_file, ca_file: Option, insecure, client:
///     Option<TlsClientConfig> }`.
///   * `crates/corro-agent/src/api/peer/mod.rs` — `build_quinn_server_config`
///     / `build_quinn_client_config`: the SERVER only requires client-cert
///     auth when `tls.client` is set (and then demands `ca_file`); the CLIENT,
///     when `ca_file` is present, runs full WebPKI verification INCLUDING
///     server-name matching against the peer's dialed IP
///     (`endpoint.connect(addr, &addr.ip().to_string())`). When `ca_file` is
///     absent it requires `insecure = true` and installs a skip-verify
///     verifier.
///
/// Consequence for a SHARED cert: a single self-signed cert has no per-peer IP
/// SANs, so enabling `ca_file` (needed for any mutual-auth mode) makes every
/// cross-node handshake fail server-name verification. The only shared-cert
/// shape that Corrosion v1.0.0 will load AND handshake cross-node is
/// encryption-only: present a server cert, skip name/CA verification on the
/// client (`insecure = true`), no `ca_file`, no `[gossip.tls.client]`. That is
/// what we emit. It layers QUIC/TLS encryption over the (already encrypted)
/// WireGuard tunnel as defense-in-depth; it deliberately adds no authentication
/// (see [`config_bytes`]).
///
/// BEFORE ENABLING, verify on your Corrosion version:
///   * `corrosion agent --config …` starts cleanly on every node (no TLS config
///     parse/verify error);
///   * `corrosion cluster members` shows every node converged (the QUIC
///     handshake actually completes across nodes).
/// Real per-node gossip authentication would need per-node certs carrying each
/// node's mgmt IP as a SAN, signed by a shared CA — which requires the mgmt IPs
/// at cert-generation time and a live cluster to validate the handshake, so it
/// is intentionally out of scope here.
fn gossip_tls_toml() -> String {
    format!(
        "plaintext = false\n[gossip.tls]\ncert_file = \"{GOSSIP_TLS_CERT_PATH}\"\nkey_file = \"{GOSSIP_TLS_KEY_PATH}\"\ninsecure = true"
    )
}

/// Refuse to generate a gossip config bound to a non-mesh address. Binding
/// `0.0.0.0`/unspecified would expose the gossip port to every interface,
/// dropping the mesh-membership trust boundary S5 relies on. This runs inside
/// [`config_bytes`] — the single config-generation path shared by `plan` and
/// `apply` — so the mgmt-IP-only bind is enforced everywhere a config is
/// produced, not merely in unit tests.
fn assert_mesh_bind(bind_addr: Ipv4Addr) {
    assert!(
        !bind_addr.is_unspecified(),
        "corrosion gossip must bind a WireGuard mesh IP, never 0.0.0.0"
    );
}

pub fn install_command(version: &str, sha256: Option<&str>) -> String {
    let verify = checksum_verify_snippet("$DLDIR/corrosion.tar.gz", "$URL", "corrosion", sha256);
    format!(
        r#"set -e
DEBIAN_FRONTEND=noninteractive apt-get update -qq 2>/dev/null
DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" ca-certificates curl tar 2>&1 >/dev/null
ARCH_RAW=$(uname -m)
case "$ARCH_RAW" in
  x86_64)  ARCH=x86_64-unknown-linux-gnu ;;
  aarch64) ARCH=aarch64-unknown-linux-gnu ;;
  *) echo "unsupported arch: $ARCH_RAW" >&2; exit 1 ;;
esac
URL="https://github.com/superfly/corrosion/releases/download/{version}/corrosion-${{ARCH}}.tar.gz"
DLDIR=$(mktemp -d)
trap 'rm -rf "$DLDIR"' EXIT
curl -fsSL --retry 3 --max-time 120 -o "$DLDIR/corrosion.tar.gz" "$URL"
{verify}
tar -xzf "$DLDIR/corrosion.tar.gz" -C "$DLDIR"
test -f "$DLDIR/corrosion" || {{ echo "corrosion binary not found in tarball" >&2; exit 1; }}
install -m 0755 "$DLDIR/corrosion" /usr/local/bin/corrosion.tmp
mv /usr/local/bin/corrosion.tmp /usr/local/bin/corrosion
echo '{version}' > /usr/local/bin/corrosion.version"#
    )
}

pub fn service_unit(iface: &str) -> String {
    format!(
        "[Unit]\nDescription=Corrosion agent\nAfter=network-online.target wg-quick@{iface}.service\nWants=network-online.target\nRequires=wg-quick@{iface}.service\n\n[Service]\nExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml\nRestart=on-failure\nRestartSec=2s\nStateDirectory=corrosion\nWorkingDirectory=/var/lib/corrosion\n\n[Install]\nWantedBy=multi-user.target\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use sha2::{Digest, Sha256};

    #[test]
    fn install_command_substitutes_version_and_arch() {
        for version in ["v1.0.0", "v1.2.3"] {
            let cmd = install_command(version, None);
            assert!(cmd.contains(version));
            assert!(cmd.contains(&format!("superfly/corrosion/releases/download/{version}")));
            assert!(cmd.contains("/usr/local/bin/corrosion.version"));
        }
        let cmd = install_command("v1.0.0", None);
        for want in [
            "x86_64)  ARCH=x86_64-unknown-linux-gnu",
            "aarch64) ARCH=aarch64-unknown-linux-gnu",
            "corrosion-${ARCH}.tar.gz",
            "install -m 0755",
        ] {
            assert!(cmd.contains(want), "missing {want} in:\n{cmd}");
        }
    }

    #[test]
    fn install_command_pins_checksum_and_verifies_before_install() {
        let pinned = install_command("v1.0.0", Some("deadbeef"));
        assert!(pinned.contains("deadbeef"));
        assert!(pinned.contains("sha256 mismatch"));
        // Verification must run before the binary is installed.
        let verify_at = pinned.find("sha256sum -c -").unwrap();
        let install_at = pinned.find("install -m 0755").unwrap();
        assert!(
            verify_at < install_at,
            "checksum verify must precede install"
        );

        let published = install_command("v1.0.0", None);
        assert!(published.contains("$URL.sha256"));
    }

    #[test]
    fn config_bytes_golden_three_host_and_stable_hash() {
        let self_ip = "100.64.0.1".parse().unwrap();
        let peers_a = vec!["100.64.0.3".parse().unwrap(), "100.64.0.2".parse().unwrap()];
        let peers_b = vec!["100.64.0.2".parse().unwrap(), "100.64.0.3".parse().unwrap()];
        let got = String::from_utf8(config_bytes(self_ip, 8787, 8080, &peers_a, false)).unwrap();
        let want = r#"# generated by coolify — do not edit
[db]
path = "/var/lib/corrosion/corrosion.db"
schema_paths = ["/etc/corrosion/schemas"]

[gossip]
addr = "100.64.0.1:8787"
bootstrap = ["100.64.0.2:8787", "100.64.0.3:8787"]
plaintext = true

[api]
addr = "127.0.0.1:8080"

[admin]
path = "/var/run/corrosion/admin.sock"
"#;
        assert_eq!(got, want);
        assert_eq!(
            Sha256::digest(config_bytes(self_ip, 8787, 8080, &peers_a, false)),
            Sha256::digest(config_bytes(self_ip, 8787, 8080, &peers_b, false))
        );
    }

    #[test]
    fn config_bytes_binds_mgmt_ip_not_wildcard() {
        let got = String::from_utf8(config_bytes(
            "100.64.0.7".parse().unwrap(),
            8787,
            8080,
            &[],
            false,
        ))
        .unwrap();
        assert!(got.contains("addr = \"100.64.0.7:8787\""));
        assert!(!got.contains("0.0.0.0"));
    }

    #[test]
    #[should_panic(expected = "never 0.0.0.0")]
    fn config_bytes_rejects_wildcard_bind() {
        let _ = config_bytes("0.0.0.0".parse().unwrap(), 8787, 8080, &[], false);
    }

    #[test]
    fn config_bytes_gossip_tls_emits_exact_verified_schema() {
        // Schema pinned to Corrosion v1.0.0. Encryption-only shared-cert shape:
        // server cert + key, client skip-verify (insecure=true), NO ca_file and
        // NO [gossip.tls.client] — the only shared-cert config v1.0.0 will load
        // and handshake cross-node (see gossip_tls_toml docs).
        let got = String::from_utf8(config_bytes(
            "100.64.0.1".parse().unwrap(),
            8787,
            8080,
            &[],
            true,
        ))
        .unwrap();
        let want_tls = format!(
            "plaintext = false\n[gossip.tls]\ncert_file = \"{GOSSIP_TLS_CERT_PATH}\"\nkey_file = \"{GOSSIP_TLS_KEY_PATH}\"\ninsecure = true\n"
        );
        assert!(got.contains(&want_tls), "TLS block mismatch in:\n{got}");
        assert!(got.contains("[gossip.tls]"));
        assert!(got.contains("insecure = true"));
        // Must NOT emit the mutual-auth fields: a no-SAN shared cert cannot pass
        // WebPKI server-name verification, so ca_file / [gossip.tls.client]
        // would break the handshake.
        assert!(!got.contains("ca_file"));
        assert!(!got.contains("[gossip.tls.client]"));
        assert!(!got.contains("plaintext = true"));
    }

    #[test]
    fn generated_config_always_binds_mgmt_ip_never_wildcard_both_modes() {
        // Enforcement runs on the real generation path (config_bytes), for both
        // the default and the opt-in TLS mode.
        for tls in [false, true] {
            let got = String::from_utf8(config_bytes(
                "100.64.0.9".parse().unwrap(),
                8787,
                8080,
                &["100.64.0.2".parse().unwrap()],
                tls,
            ))
            .unwrap();
            assert!(got.contains("addr = \"100.64.0.9:8787\""));
            assert!(!got.contains("0.0.0.0"));
            assert!(!got.contains("addr = \"0"));
        }
    }

    #[test]
    fn config_bytes_empty_peers_and_schema_columns() {
        let got = String::from_utf8(config_bytes(
            "100.64.0.1".parse().unwrap(),
            8787,
            8080,
            &[],
            false,
        ))
        .unwrap();
        assert!(got.contains("bootstrap = []"));
        for want in [
            "container_name  TEXT NOT NULL DEFAULT ''",
            "namespace       TEXT NOT NULL DEFAULT ''",
            "state           TEXT NOT NULL DEFAULT ''",
            "health          TEXT NOT NULL DEFAULT 'unknown'",
        ] {
            assert!(COOLIFY_SCHEMA_SQL.contains(want), "schema missing {want}");
        }
        assert!(!COOLIFY_SCHEMA_SQL.contains("healthy"));
        for line in COOLIFY_SCHEMA_SQL.lines().map(str::trim) {
            if line.contains("NOT NULL") {
                assert!(line.contains("DEFAULT"), "missing DEFAULT: {line}");
            }
        }
    }

    #[test]
    fn service_unit_contains_interface() {
        let got = service_unit("wg0");
        for want in [
            "After=network-online.target wg-quick@wg0.service",
            "Requires=wg-quick@wg0.service",
            "ExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml",
        ] {
            assert!(got.contains(want), "missing {want} in:\n{got}");
        }
    }
}
