use std::net::Ipv4Addr;

pub const COOLIFY_SCHEMA_SQL: &str = "CREATE TABLE service_endpoints (\n    container_id    TEXT NOT NULL DEFAULT '' PRIMARY KEY,\n    container_name  TEXT NOT NULL DEFAULT '',\n    namespace       TEXT NOT NULL DEFAULT '',\n    host_mgmt_ip    TEXT NOT NULL DEFAULT '',\n    container_ip    TEXT NOT NULL DEFAULT '',\n    state           TEXT NOT NULL DEFAULT '',\n    health          TEXT NOT NULL DEFAULT 'unknown',\n    updated_at      INTEGER NOT NULL DEFAULT 0\n);\n";

pub fn config_bytes(
    bind_addr: Ipv4Addr,
    gossip_port: u16,
    api_port: u16,
    peers: &[Ipv4Addr],
) -> Vec<u8> {
    let mut sorted = peers.to_vec();
    sorted.sort();
    let bootstrap = sorted
        .iter()
        .map(|p| format!("\"{p}:{gossip_port}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!("# generated by cooldctl — do not edit\n[db]\npath = \"/var/lib/corrosion/corrosion.db\"\nschema_paths = [\"/etc/corrosion/schemas\"]\n\n[gossip]\naddr = \"{bind_addr}:{gossip_port}\"\nbootstrap = [{bootstrap}]\nplaintext = true\n\n[api]\naddr = \"127.0.0.1:{api_port}\"\n\n[admin]\npath = \"/var/run/corrosion/admin.sock\"\n").into_bytes()
}

pub fn install_command(version: &str) -> String {
    format!(
        r#"set -e
DEBIAN_FRONTEND=noninteractive apt-get update -qq 2>/dev/null
DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" ca-certificates curl tar 2>&1 >/dev/null
ARCH_RAW=$(uname -m)
case "$ARCH_RAW" in
  x86_64)  ARCH=x86_64-unknown-linux-gnu ;;
  aarch64) ARCH=aarch64-unknown-linux-gnu ;;
  *) echo "unsupported arch: $ARCH_RAW" >&2; exit 1 ;;
esac
URL="https://github.com/superfly/corrosion/releases/download/{version}/corrosion-${{ARCH}}.tar.gz"
DLDIR=$(mktemp -d)
trap 'rm -rf "$DLDIR"' EXIT
curl -fsSL --retry 3 --max-time 120 -o "$DLDIR/corrosion.tar.gz" "$URL"
tar -xzf "$DLDIR/corrosion.tar.gz" -C "$DLDIR"
test -f "$DLDIR/corrosion" || {{ echo "corrosion binary not found in tarball" >&2; exit 1; }}
install -m 0755 "$DLDIR/corrosion" /usr/local/bin/corrosion.tmp
mv /usr/local/bin/corrosion.tmp /usr/local/bin/corrosion
echo '{version}' > /usr/local/bin/corrosion.version"#
    )
}

pub fn service_unit(iface: &str) -> String {
    format!(
        "[Unit]\nDescription=Corrosion agent\nAfter=network-online.target wg-quick@{iface}.service\nWants=network-online.target\nRequires=wg-quick@{iface}.service\n\n[Service]\nExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml\nRestart=on-failure\nRestartSec=2s\nStateDirectory=corrosion\nWorkingDirectory=/var/lib/corrosion\n\n[Install]\nWantedBy=multi-user.target\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use sha2::{Digest, Sha256};

    #[test]
    fn install_command_substitutes_version_and_arch() {
        for version in ["v1.0.0", "v1.2.3"] {
            let cmd = install_command(version);
            assert!(cmd.contains(version));
            assert!(cmd.contains(&format!("superfly/corrosion/releases/download/{version}")));
            assert!(cmd.contains("/usr/local/bin/corrosion.version"));
        }
        let cmd = install_command("v1.0.0");
        for want in [
            "x86_64)  ARCH=x86_64-unknown-linux-gnu",
            "aarch64) ARCH=aarch64-unknown-linux-gnu",
            "corrosion-${ARCH}.tar.gz",
            "install -m 0755",
        ] {
            assert!(cmd.contains(want), "missing {want} in:\n{cmd}");
        }
    }

    #[test]
    fn config_bytes_golden_three_host_and_stable_hash() {
        let self_ip = "100.64.0.1".parse().unwrap();
        let peers_a = vec!["100.64.0.3".parse().unwrap(), "100.64.0.2".parse().unwrap()];
        let peers_b = vec!["100.64.0.2".parse().unwrap(), "100.64.0.3".parse().unwrap()];
        let got = String::from_utf8(config_bytes(self_ip, 8787, 8080, &peers_a)).unwrap();
        let want = r#"# generated by cooldctl — do not edit
[db]
path = "/var/lib/corrosion/corrosion.db"
schema_paths = ["/etc/corrosion/schemas"]

[gossip]
addr = "100.64.0.1:8787"
bootstrap = ["100.64.0.2:8787", "100.64.0.3:8787"]
plaintext = true

[api]
addr = "127.0.0.1:8080"

[admin]
path = "/var/run/corrosion/admin.sock"
"#;
        assert_eq!(got, want);
        assert_eq!(
            Sha256::digest(config_bytes(self_ip, 8787, 8080, &peers_a)),
            Sha256::digest(config_bytes(self_ip, 8787, 8080, &peers_b))
        );
    }

    #[test]
    fn config_bytes_empty_peers_and_schema_columns() {
        let got = String::from_utf8(config_bytes("100.64.0.1".parse().unwrap(), 8787, 8080, &[]))
            .unwrap();
        assert!(got.contains("bootstrap = []"));
        for want in [
            "container_name  TEXT NOT NULL DEFAULT ''",
            "namespace       TEXT NOT NULL DEFAULT ''",
            "state           TEXT NOT NULL DEFAULT ''",
            "health          TEXT NOT NULL DEFAULT 'unknown'",
        ] {
            assert!(COOLIFY_SCHEMA_SQL.contains(want), "schema missing {want}");
        }
        assert!(!COOLIFY_SCHEMA_SQL.contains("healthy"));
        for line in COOLIFY_SCHEMA_SQL.lines().map(str::trim) {
            if line.contains("NOT NULL") {
                assert!(line.contains("DEFAULT"), "missing DEFAULT: {line}");
            }
        }
    }

    #[test]
    fn service_unit_contains_interface() {
        let got = service_unit("wg0");
        for want in [
            "After=network-online.target wg-quick@wg0.service",
            "Requires=wg-quick@wg0.service",
            "ExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml",
        ] {
            assert!(got.contains(want), "missing {want} in:\n{got}");
        }
    }
}
